#!/usr/bin/python
import os
import sys
import subprocess
import re
import yaml
import argparse

foo = """
    output=subprocess.check_output("parsechangelog | grep Version", shell=True)
    ver = output.split(":")[1].strip()
    match = re.compile(".*([0-9]+\.[0-9]+\.[0-9]+).*").match(ver)
    if match:
        version = match.group(1)
    print "-> %s <-"%ver
    print "-> %s <-"%version
    """

def is_snapshot(repo_uri,repo_name):
    if explain_mode:
        print "cd %s/%s"%(script_dir,repo_name)
        print "parsechangelog | grep Version"
    else:
        os.chdir("%s/%s"%(script_dir,repo_name))
        output=subprocess.check_output("parsechangelog | grep Version", shell=True)
        ver = output.split(":")[1].strip()
        match = re.compile(".*([0-9]+)\.([0-9]+)\.([0-9]+).*").match(ver)
        if match:
            ver_maj = int(match.group(1))
            ver_min = int(match.group(2))
            ver_rev = int(match.group(3))
        else:
            sys.exit(-1)

        if ver == "%d.%d.%d"%(ver_maj,ver_min,ver_rev):
            return False;
        else:
            return True;

def detect_version(repo_uri,repo_name):
    if explain_mode:
        print "parsechangelog | grep Version"
    else:
        os.chdir("%s/%s"%(script_dir,repo_name))
        output=subprocess.check_output("parsechangelog | grep Version", shell=True)
        ver = output.split(":")[1].strip()
        match = re.compile(".*([0-9]+)\.([0-9]+)\.([0-9]+).*").match(ver)
        #match = re.compile(".*([0-9]+\.[0-9]+\.[0-9]+).*").match(ver)
        if match:
            #version = match.group(1)
            ver_maj = int(match.group(1))
            ver_min = int(match.group(2))
            ver_rev = int(match.group(3))
            print "-> %s <-"%ver
            print "-> %d-%d-%d <-"%(ver_maj,ver_min,ver_rev)
        else:
            print "Error detecting version"
        if is_snapshot(repo_uri,repo_name):
            print "Snap!!"
        else:
            print "Release"

def snapshot_repo(repo_uri,repo_name):
    if explain_mode:
        print "cd %s/%s"%(script_dir,repo_name)
    os.chdir("%s/%s"%(script_dir,repo_name))
    output=subprocess.check_output("parsechangelog | grep Version", shell=True)
    ver = output.split(":")[1].strip()
    match = re.compile(".*([0-9]+)\.([0-9]+)\.([0-9]+).*").match(ver)
    if match:
        ver_maj = int(match.group(1))
        ver_min = int(match.group(2))
        if is_snapshot(repo_uri,repo_name):
            ver_rev = int(match.group(3))
        else:
            ver_rev = int(match.group(3)) + 1
        snap_version = "%d.%d.%d"%(ver_maj,ver_min,ver_rev)
    else:
        print "Error detecting version"
        sys.exit(0);

    if explain_mode:
        print "git-dch -N %s -S"%snap_version
        if is_snapshot(repo_uri,repo_name):
            print "git-buildpackage --git-tag-only --git-ignore-new"
    else:
        status = os.system("git-dch -N %s -S"%snap_version)
        if is_snapshot(repo_uri,repo_name):
            status = os.system("git-buildpackage --git-tag-only --git-ignore-new")

def build_repo(repo_uri,repo_name,source):
    if (not os.path.isdir("%s/%s"%(script_dir,repo_name))):
        print "ERROR: Unable to find %s, try cloning first"%repo_name
        sys.exit(os.EX_OSFILE)
    if source:
        if explain_mode:
            print "cd %s/%s"%(script_dir,repo_name)
            print "dpkg-buildpackage -S -us -uc"
        else:
            os.chdir("%s/%s"%(script_dir,repo_name))
            status = os.system("dpkg-buildpackage -S -us -uc")
    else:
        if explain_mode:
            print "cd %s/%s"%(script_dir,repo_name)
            print "dpkg-buildpackage -us -uc"
        else:
            os.chdir("%s/%s"%(script_dir,repo_name))
            status = os.system("dpkg-buildpackage -us -uc")

def lint_repo(repo_uri,repo_name):
    if explain_mode:
        print "cd %s"%(script_dir)
    else:
        os.chdir(script_dir)

    if explain_mode:
        print "lintian %s*_source.changes"%repo_name
    else:
        status = os.system("lintian %s*_source.changes"%repo_name)

def clone_repo(repo_uri,repo_name):
    if (os.path.isdir("%s/%s"%(script_dir,repo_name))):
        if not explain_mode:
            print "Repository: %s already cloned"%repo_name
    else:
        if explain_mode:
            print "cd %s"%(script_dir)
            print "git clone %s %s"%(repo_uri,repo_name)
        else:
            os.chdir(script_dir)
            status = os.system("git clone %s %s"%(repo_uri,repo_name))

################################

def cmd_purge(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack clone',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    if explain_mode:
        print "cd %s"%(script_dir)
        print "rm -f *.changes *.dsc *.deb *.gz *.build *.upload"
    else:
        os.chdir(script_dir)
        status = os.system("rm -f *.changes *.dsc *.deb *.gz *.build *.upload")

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "Error in configuration file:", e

    for repo in repos:
        if explain_mode:
            print "rm -rf %s"%repo['name']
        else:
            status = os.system("rm -rf %s"%repo['name'])

def cmd_clean(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack clone',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    for repo in repos:
        if explain_mode:
            print "cd %s/%s"%(script_dir,repo['name'])
            print "dh_clean"
        else:
            if os.path.isdir("%s/%s"%(script_dir,repo['name'])):
                os.chdir("%s/%s"%(script_dir,repo['name']))
                status = os.system("dh_clean")

    if explain_mode:
        print "cd %s"%(script_dir)
        print "rm -f *.changes *.dsc *.deb *.gz *.build *.upload"
    else:
        os.chdir(script_dir)
        status = os.system("rm -f *.changes *.dsc *.deb *.gz *.build *.upload")

def cmd_clone(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack clone',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "Error in configuration file:", e

    for repo in repos:
        clone_repo(repo['repo'],repo['name'])

def cmd_build(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack build',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    parser.add_argument('-s', '--source', help='Source only build for upload to PPA', action='store_true')
    parser.add_argument('package', nargs='?', default=None, help='Package (default: all)')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    print "Source: %s"%(args.source)

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    if args.package is None:
        for repo in repos:
            build_repo(repo['repo'],repo['name'],args.source)
    else:
        for repo in repos:
            if repo['name'] == args.package:
                build_repo(repo['repo'],repo['name'],args.source)

def cmd_version(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack version',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    parser.add_argument('package', nargs='?', default=None, help='Package (default: all)')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    if args.package is None:
        for repo in repos:
            print "%s"%repo['name']
            detect_version(repo['repo'],repo['name'])
    else:
        for repo in repos:
            if repo['name'] == args.package:
                print "%s"%repo['name']
                detect_version(repo['repo'],repo['name'])

def cmd_snapshot(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack snapshot',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    parser.add_argument('-s', '--source', help='Source only build for upload to PPA', action='store_true')
    parser.add_argument('package', nargs=1, default=None, help='Package')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    for repo in repos:
        if repo['name'] == args.package[0]:
            snapshot_repo(repo['repo'],repo['name'])
	    build_repo(repo['repo'],repo['name'],args.source)

def cmd_lint(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack clone',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    for repo in repos:
        lint_repo(repo['repo'],repo['name'])

def cmd_pull(argv):
    argv = argv[2:]
    parser = argparse.ArgumentParser(prog='metapack clone',epilog='MetaPack Package Management Tool')
    parser.add_argument('-x', '--explain', help='Explain operations without executing', action='store_true')
    #parser.add_argument('-g', '--group', nargs='+', default=['personal'], help='Task Group(s) (default: %(default)s)')
    args = parser.parse_args(argv)
    global explain_mode
    explain_mode = args.explain

    try:
        repos = yaml.load(file('repos.yaml', 'r'))
    except yaml.YAMLError, e:
        print "ERROR: configuration file:", e

    for repo in repos:
        if (not os.path.isdir("%s/%s"%(script_dir,repo['name']))):
            print "ERROR: Unable to find %s, try cloning first"%repo['name']
            sys.exit(os.EX_OSFILE)
        if explain_mode:
            print "cd %s/%s"%(script_dir,repo['name'])
            print "git pull origin master"
        else:
            os.chdir("%s/%s"%(script_dir,repo['name']))
            status = os.system("git pull origin master")

def metapack_usage():
    print """MetaPack Package Management Tool
------------------------------------------------------------
usage: metapack [--version] COMMAND [ARGS]

Common Commands:
\tmetapack clone\t\tclone repos
\tmetapack build\t\tbuild repos
\tmetapack version\trepo version information
\tmetapack snapshot\trepo version information
\tmetapack clean\t\tdeletes *.changes *.dsc *.deb *.gz *.build *.upload

Use 'metapack COMMAND -h' for more information about a command."""
    sys.exit(os.EX_USAGE)

################################

if __name__ == '__main__':
    global script_dir
    script_dir = os.path.abspath(os.path.dirname(sys.argv[0]))

    if len(sys.argv) == 1:
        metapack_usage()

    else:
        if (sys.argv[1] == '--version'):
            version = "0.0.1"
            print "Metapack Version %s"%version
            sys.exit(os.EX_OK)
        if (sys.argv[1] == 'clean'):
            cmd_clean(sys.argv)
        elif (sys.argv[1] == 'purge'):
            cmd_purge(sys.argv)
        elif (sys.argv[1] == 'clone'):
            cmd_clone(sys.argv)
        elif (sys.argv[1] == 'build'):
            cmd_build(sys.argv)
        elif (sys.argv[1] == 'version'):
            cmd_version(sys.argv)
        elif (sys.argv[1] == 'snapshot'):
            cmd_snapshot(sys.argv)
        elif (sys.argv[1] == 'lint'):
            cmd_lint(sys.argv)
        elif (sys.argv[1] == 'pull'):
            cmd_pull(sys.argv)
        else:
            metapack_usage()
